from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time

driver = webdriver.Chrome()
driver.maximize_window()
driver.get("https://www.google.com/")
driver.find_element_by_xpath('/html/body/div/div[2]/div/div/div/div[2]/div[2]/div/a').click()
time.sleep(2)
driver.find_element_by_name("identifier").send_keys("hermandanila19@gmail.com")
time.sleep(3)
driver.find_element_by_xpath('/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div/div[2]/div/div[2]/div/div[1]/div/span/span').click()
time.sleep(2)
driver.find_element_by_name("password").send_keys("sman60jakarta")
time.sleep(3)
driver.find_element_by_xpath('/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div/div[2]/div/div[2]/div/div[1]/div/span/span').click()
time.sleep(3)
# driver.find_element_by_xpath('/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div/div[2]/div/div[1]/div/form/span/section/div/div/div/ul/li[1]/div/div[2]').click()
# time.sleep(2)
# driver.find_element_by_name("knowledgePreregisteredEmailResponse").send_keys("nadellasyaputri@gmail.com")
# driver.find_element_by_xpath('/html/body/div[1]/div[1]/div[2]/div/div[2]/div/div/div[2]/div/div[2]/div/div[1]/div/span/span').click()
# time.sleep(3)
driver.get("https://www.google.com/")
driver.find_element_by_name("q").send_keys("youtube robot gaptek buat alat anti maling")
time.sleep(3)
driver.find_element_by_xpath('/html/body/div/div[3]/form/div[2]/div[1]/div[3]/center/input[1]').click()
time.sleep(3)
driver.find_element_by_xpath('/html/body/div[6]/div[2]/div[9]/div[1]/div[2]/div/div[2]/div[2]/div/div/div[1]/g-section-with-header/div[2]/g-scrolling-carousel/div[1]/div/div/div[1]/g-inner-card/div/a/div[2]/div').click()
time.sleep(3)
driver.find_element_by_xpath('/html/body/div[6]/div[2]/div[9]/div[1]/div[2]/div/div[2]/div[2]/div/div/div[1]/g-section-with-header/div[2]/g-scrolling-carousel/div[1]/div/div/div[1]/g-inner-card/div/a/div[2]/div').click()
time.sleep(10)
driver.close()
print ("success running robot program")
